// <auto-generated />
using System;
using CuaHangDienThoai.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CuaHangDienThoai.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CuaHangDienThoai.Models.ChiTietDonHang", b =>
                {
                    b.Property<int>("Id_ChiTietDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_ChiTietDonHang"));

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Id_DonHang")
                        .HasColumnType("int");

                    b.Property<int>("Id_SanPham")
                        .HasColumnType("int");

                    b.Property<int>("So_Luong")
                        .HasColumnType("int");

                    b.HasKey("Id_ChiTietDonHang");

                    b.HasIndex("Id_DonHang");

                    b.HasIndex("Id_SanPham");

                    b.ToTable("ChiTietDonHangs");
                });

            modelBuilder.Entity("CuaHangDienThoai.Models.DanhGia", b =>
                {
                    b.Property<int>("Id_DanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_DanhGia"));

                    b.Property<int>("Id_DonHang")
                        .HasColumnType("int");

                    b.Property<int>("Id_NguoiDung")
                        .HasColumnType("int");

                    b.Property<int>("Id_SanPham")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ngay_DanhGia")
                        .HasColumnType("datetime");

                    b.Property<string>("Nhan_Xet")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("So_Sao")
                        .HasColumnType("int");

                    b.HasKey("Id_DanhGia");

                    b.HasIndex("Id_DonHang");

                    b.HasIndex("Id_NguoiDung");

                    b.HasIndex("Id_SanPham");

                    b.ToTable("DanhGias", t =>
                        {
                            t.HasCheckConstraint("CK_DanhGia_SoSao", "[So_Sao] BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("CuaHangDienThoai.Models.DanhMuc", b =>
                {
                    b.Property<int>("Id_DanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_DanhMuc"));

                    b.Property<string>("Ten_DanhMuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_DanhMuc");

                    b.ToTable("DanhMucs");
                });

            modelBuilder.Entity("CuaHangDienThoai.Models.DonHang", b =>
                {
                    b.Property<int>("Id_DonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_DonHang"));

                    b.Property<string>("Dia_Chi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_NguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ngay_Tao")
                        .HasColumnType("datetime");

                    b.Property<decimal>("Tong_Tien")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id_DonHang");

                    b.HasIndex("Id_NguoiDung");

                    b.ToTable("DonHangs");
                });

            modelBuilder.Entity("CuaHangDienThoai.Models.NguoiDung", b =>
                {
                    b.Property<int>("Id_NguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_NguoiDung"));

                    b.Property<string>("Dia_Chi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ho_Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Mat_Khau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("Ngay_Tao")
                        .HasColumnType("datetime");

                    b.Property<string>("So_Dien_Thoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Ten_Dang_Nhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_NguoiDung");

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("CuaHangDienThoai.Models.SanPham", b =>
                {
                    b.Property<int>("Id_SanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_SanPham"));

                    b.Property<string>("Anh_Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BaoHanh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DungLuongLuuTru")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("Id_DanhMuc")
                        .HasColumnType("int");

                    b.Property<string>("KichThuocManHinh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Mo_Ta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ram")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("SoKheCamSim")
                        .HasColumnType("int");

                    b.Property<int>("So_Luong")
                        .HasColumnType("int");

                    b.Property<string>("Ten_SanPham")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id_SanPham");

                    b.HasIndex("Id_DanhMuc");

                    b.ToTable("SanPhams");
                });

            modelBuilder.Entity("CuaHangDienThoai.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("CuaHangDienThoai.Models.DonHang", "DonHang")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("Id_DonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CuaHangDienThoai.Models.SanPham", "SanPham")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("Id_SanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("CuaHangDienThoai.Models.DanhGia", b =>
                {
                    b.HasOne("CuaHangDienThoai.Models.DonHang", "DonHang")
                        .WithMany("DanhGias")
                        .HasForeignKey("Id_DonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CuaHangDienThoai.Models.NguoiDung", "NguoiDung")
                        .WithMany("DanhGias")
                        .HasForeignKey("Id_NguoiDung")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CuaHangDienThoai.Models.SanPham", "SanPham")
                        .WithMany("DanhGias")
                        .HasForeignKey("Id_SanPham")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("NguoiDung");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("CuaHangDienThoai.Models.DonHang", b =>
                {
                    b.HasOne("CuaHangDienThoai.Models.NguoiDung", "NguoiDung")
                        .WithMany("DonHangs")
                        .HasForeignKey("Id_NguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("CuaHangDienThoai.Models.SanPham", b =>
                {
                    b.HasOne("CuaHangDienThoai.Models.DanhMuc", "DanhMuc")
                        .WithMany("SanPhams")
                        .HasForeignKey("Id_DanhMuc")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DanhMuc");
                });

            modelBuilder.Entity("CuaHangDienThoai.Models.DanhMuc", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("CuaHangDienThoai.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("DanhGias");
                });

            modelBuilder.Entity("CuaHangDienThoai.Models.NguoiDung", b =>
                {
                    b.Navigation("DanhGias");

                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("CuaHangDienThoai.Models.SanPham", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("DanhGias");
                });
#pragma warning restore 612, 618
        }
    }
}
